name: TouchGrass
options:
  bundleIdPrefix: com.pop
  deploymentTarget:
    iOS: "16.4"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "${BUILD_NUMBER}"
    DEVELOPMENT_TEAM: QL8TU9W7QA

targets:
  TouchGrass:
    type: application
    platform: iOS
    sources:
      - path: TouchGrass
      - path: Shared
      - path: TouchGrass/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pop.touchgrass
        INFOPLIST_FILE: TouchGrass/Info.plist
        GENERATE_INFOPLIST_FILE: false
        CODE_SIGN_ENTITLEMENTS: TouchGrass/TouchGrass.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: "1"
    dependencies:
      - target: TouchGrassMonitor
      - target: TouchGrassWidgets

  TouchGrassMonitor:
    type: app-extension
    platform: iOS
    sources:
      - path: TouchGrassMonitor
      - path: Shared
    info:
      path: TouchGrassMonitor/Info.plist
      properties:
        CFBundleDisplayName: TouchGrassMonitor
        NSExtension:
          NSExtensionPointIdentifier: com.apple.deviceactivity.monitor-extension
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).TouchGrassMonitor
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pop.touchgrass.monitor
        INFOPLIST_FILE: TouchGrassMonitor/Info.plist
        GENERATE_INFOPLIST_FILE: false
        CODE_SIGN_ENTITLEMENTS: TouchGrassMonitor/TouchGrassMonitor.entitlements

  TouchGrassWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: TouchGrassWidgets
      - path: Shared
    info:
      path: TouchGrassWidgets/Info.plist
      properties:
        CFBundleDisplayName: TouchGrassWidgets
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pop.touchgrass.widgets
        INFOPLIST_FILE: TouchGrassWidgets/Info.plist
        GENERATE_INFOPLIST_FILE: false
